connections:
  source:
    name: RedisLabsCDC #database name
    db: RedisLabsCDC #database
    hostname: redis-cdc-redisconf2021.demo.redislabs.com
    port: 1433
    username: sa
    password: Redis@123
    type: mssqlserver #this value can not be changed for mssqlserver
    jdbcUrl: "jdbc:sqlserver://redis-cdc-redisconf2021.demo.redislabs.com:1433;database=RedisLabsCDC"
    maximumPoolSize: 10
    minimumIdle: 2
    tableName: dbo.emp
    batchSize: 10
    loadQueryFile: insert.sql
    csvFile: emp.csv
    select: select.sql
    updatedSelect: updatedSelect.sql
    update: update.sql
    delete: delete.sql
    #loadQuery: "select * from dbo.emp"
    iteration: 100000