connections:
  source:
    username: sa # DB user
    password: Redis@123 # DB password
    type: mssql # this value can not be changed for oracle
    name: rc-mssql # database pool name
    jdbcUrl: "jdbc:sqlserver://127.0.0.1:1433;database=RedisConnect"
    tableName: dbo.emp # table name in schema.table format
    batchSize: 5000 # batch size
    truncateBeforeLoad: true # default is true and the table won't be truncated before initial load. Applies to both crudloader and loadsql options.
    #loadQueryFile: insert.sql #insert query for loadsql option
    csvFile: emp_100k.csv #emp.csv.sqlserver # csv data with header to load (crudloader option)
    #select: select.sql.sqlserver # select query for the continuous crud (crudloader option)
    updatedSelect: # updatedSelect.sql #updated select query for the continuous crud
    update: # update.sql # update query for the continuous crud (crudloader option)
    delete: # delete.sql # delete query for the continuous crud (crudloader option)
    #loadQuery: "select * from dbo.emp" #This can be used instead of loadQueryFile property
    iteration: 1 # number of iterations to run (crudloader option)
